server:
  port: 8090
spring:
  application:
    name: shop
  datasource:
    password: password
    url: jdbc:postgresql://localhost:50/shop
    username: kosmala
  jpa:
     hibernate:
       ddl-auto: create-drop
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         format_sql: true
     show-sql: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    orderConfirmation: orderConfirmation.queue
    accountConfirmation: accountConfirmation.queue
    orderChangeStatus: orderChangeStatus.queue
  routing-keys:
     internal-orderConfirmation: internal.orderConfirmation.routing-key
     internal-accountConfirmation: internal.accountConfirmation.routing-key
     internal-orderChangeStatus: internal.orderChangeStatus.routing-key
